-- TripZone company-grade DDL v2
-- Oracle-style schema

CREATE TABLE MEMBER_GRADES (
    GRADE_NO NUMBER(10) NOT NULL,
    GRADE_CODE VARCHAR2(30) NOT NULL,
    GRADE_NAME VARCHAR2(50) NOT NULL,
    MIN_TOTAL_AMOUNT NUMBER(12) DEFAULT 0 NOT NULL,
    MIN_STAY_COUNT NUMBER(10) DEFAULT 0 NOT NULL,
    MILEAGE_RATE NUMBER(5,2) DEFAULT 0 NOT NULL,
    BENEFIT_DESC VARCHAR2(500),
    STATUS VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
    SORT_ORDER NUMBER(3) DEFAULT 1 NOT NULL,
    REG_DATE DATE DEFAULT SYSDATE NOT NULL,
    UPD_DATE DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_MEMBER_GRADES PRIMARY KEY (GRADE_NO),
    CONSTRAINT UK_MEMBER_GRADES_CODE UNIQUE (GRADE_CODE),
    CONSTRAINT CK_MEMBER_GRADES_MIN_TOTAL_AMOUNT CHECK (MIN_TOTAL_AMOUNT >= 0),
    CONSTRAINT CK_MEMBER_GRADES_MIN_STAY_COUNT CHECK (MIN_STAY_COUNT >= 0),
    CONSTRAINT CK_MEMBER_GRADES_MILEAGE_RATE CHECK (MILEAGE_RATE >= 0),
    CONSTRAINT CK_MEMBER_GRADES_STATUS CHECK (STATUS IN ('ACTIVE', 'INACTIVE')),
    CONSTRAINT CK_MEMBER_GRADES_SORT_ORDER CHECK (SORT_ORDER > 0)
);

CREATE SEQUENCE SEQ_MEMBER_GRADES START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE TABLE USERS (
    USER_NO NUMBER(10) NOT NULL,
    USER_NAME VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(100) NOT NULL,
    PHONE VARCHAR2(20) NOT NULL,
    GRADE_NO NUMBER(10),
    MILEAGE NUMBER(12) DEFAULT 0 NOT NULL,
    ENABLED CHAR(1) DEFAULT '1' NOT NULL,
    USER_STATUS VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
    DELETED_AT DATE,
    REG_DATE DATE DEFAULT SYSDATE NOT NULL,
    UPD_DATE DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_USERS PRIMARY KEY (USER_NO),
    CONSTRAINT UK_USERS_EMAIL UNIQUE (EMAIL),
    CONSTRAINT FK_USERS_GRADE FOREIGN KEY (GRADE_NO) REFERENCES MEMBER_GRADES(GRADE_NO),
    CONSTRAINT CK_USERS_ENABLED CHECK (ENABLED IN ('0', '1')),
    CONSTRAINT CK_USERS_MILEAGE CHECK (MILEAGE >= 0),
    CONSTRAINT CK_USERS_STATUS CHECK (USER_STATUS IN ('ACTIVE', 'DORMANT', 'BLOCKED', 'DELETED'))
);

CREATE SEQUENCE SEQ_USERS START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE INDEX IDX_USERS_STATUS ON USERS (USER_STATUS, ENABLED);

CREATE TABLE USER_AUTH_PROVIDERS (
    USER_AUTH_NO NUMBER(10) NOT NULL,
    USER_NO NUMBER(10) NOT NULL,
    PROVIDER_CODE VARCHAR2(20) NOT NULL,
    PROVIDER_USER_ID VARCHAR2(200),
    LOGIN_ID VARCHAR2(100),
    PASSWORD_HASH VARCHAR2(255),
    CONNECTED_AT DATE DEFAULT SYSDATE NOT NULL,
    LAST_LOGIN_AT DATE,
    REG_DATE DATE DEFAULT SYSDATE NOT NULL,
    UPD_DATE DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_USER_AUTH_PROVIDERS PRIMARY KEY (USER_AUTH_NO),
    CONSTRAINT FK_USER_AUTH_PROVIDERS_USER FOREIGN KEY (USER_NO) REFERENCES USERS(USER_NO),
    CONSTRAINT UK_USER_AUTH_PROVIDER UNIQUE (USER_NO, PROVIDER_CODE),
    CONSTRAINT UK_USER_AUTH_PROVIDER_USER UNIQUE (PROVIDER_CODE, PROVIDER_USER_ID),
    CONSTRAINT UK_USER_AUTH_LOGIN_ID UNIQUE (LOGIN_ID),
    CONSTRAINT CK_USER_AUTH_PROVIDER_CODE CHECK (PROVIDER_CODE IN ('LOCAL', 'GOOGLE', 'KAKAO', 'NAVER'))
);

CREATE SEQUENCE SEQ_USER_AUTH_PROVIDERS START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE TABLE USER_ROLES (
    USER_ROLE_NO NUMBER(10) NOT NULL,
    USER_NO NUMBER(10) NOT NULL,
    ROLE_CODE VARCHAR2(30) NOT NULL,
    REG_DATE DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_USER_ROLES PRIMARY KEY (USER_ROLE_NO),
    CONSTRAINT FK_USER_ROLES_USER FOREIGN KEY (USER_NO) REFERENCES USERS(USER_NO),
    CONSTRAINT UK_USER_ROLES_USER_ROLE UNIQUE (USER_NO, ROLE_CODE),
    CONSTRAINT CK_USER_ROLES_ROLE_CODE CHECK (ROLE_CODE IN ('ROLE_USER', 'ROLE_HOST', 'ROLE_ADMIN'))
);

CREATE SEQUENCE SEQ_USER_ROLES START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE TABLE HOST_PROFILES (
    HOST_NO NUMBER(10) NOT NULL,
    USER_NO NUMBER(10) NOT NULL,
    BUSINESS_NAME VARCHAR2(100) NOT NULL,
    BUSINESS_NUMBER VARCHAR2(50) NOT NULL,
    OWNER_NAME VARCHAR2(100) NOT NULL,
    APPROVAL_STATUS VARCHAR2(20) DEFAULT 'PENDING' NOT NULL,
    APPROVED_BY NUMBER(10),
    APPROVED_AT DATE,
    REJECT_REASON VARCHAR2(300),
    SUSPENDED_AT DATE,
    REG_DATE DATE DEFAULT SYSDATE NOT NULL,
    UPD_DATE DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_HOST_PROFILES PRIMARY KEY (HOST_NO),
    CONSTRAINT UK_HOST_PROFILES_USER UNIQUE (USER_NO),
    CONSTRAINT UK_HOST_PROFILES_BUSINESS_NUMBER UNIQUE (BUSINESS_NUMBER),
    CONSTRAINT FK_HOST_PROFILES_USER FOREIGN KEY (USER_NO) REFERENCES USERS(USER_NO),
    CONSTRAINT FK_HOST_PROFILES_APPROVED_BY FOREIGN KEY (APPROVED_BY) REFERENCES USERS(USER_NO),
    CONSTRAINT CK_HOST_PROFILES_APPROVAL_STATUS CHECK (APPROVAL_STATUS IN ('PENDING', 'APPROVED', 'REJECTED', 'SUSPENDED'))
);

CREATE SEQUENCE SEQ_HOST_PROFILES START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE INDEX IDX_HOST_PROFILES_STATUS ON HOST_PROFILES (APPROVAL_STATUS, USER_NO);

CREATE TABLE EVENTS (
    EVENT_NO NUMBER(10) NOT NULL,
    ADMIN_USER_NO NUMBER(10) NOT NULL,
    TITLE VARCHAR2(200) NOT NULL,
    CONTENT CLOB NOT NULL,
    THUMBNAIL_URL VARCHAR2(300),
    START_DATE DATE NOT NULL,
    END_DATE DATE NOT NULL,
    EVENT_STATUS VARCHAR2(20) DEFAULT 'DRAFT' NOT NULL,
    VIEW_COUNT NUMBER(10) DEFAULT 0 NOT NULL,
    REG_DATE DATE DEFAULT SYSDATE NOT NULL,
    UPD_DATE DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_EVENTS PRIMARY KEY (EVENT_NO),
    CONSTRAINT FK_EVENTS_ADMIN FOREIGN KEY (ADMIN_USER_NO) REFERENCES USERS(USER_NO),
    CONSTRAINT CK_EVENTS_DATE CHECK (END_DATE >= START_DATE),
    CONSTRAINT CK_EVENTS_STATUS CHECK (EVENT_STATUS IN ('DRAFT', 'ONGOING', 'ENDED', 'HIDDEN')),
    CONSTRAINT CK_EVENTS_VIEW_COUNT CHECK (VIEW_COUNT >= 0)
);

CREATE SEQUENCE SEQ_EVENTS START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE TABLE COUPONS (
    COUPON_NO NUMBER(10) NOT NULL,
    ISSUED_BY_USER_NO NUMBER(10) NOT NULL,
    COUPON_NAME VARCHAR2(100) NOT NULL,
    COUPON_CODE VARCHAR2(50) NOT NULL,
    DISCOUNT_TYPE VARCHAR2(20) NOT NULL,
    DISCOUNT_VALUE NUMBER(10) NOT NULL,
    MAX_DISCOUNT_AMOUNT NUMBER(10),
    MIN_ORDER_AMOUNT NUMBER(10) DEFAULT 0 NOT NULL,
    START_DATE DATE NOT NULL,
    END_DATE DATE NOT NULL,
    STATUS VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
    REG_DATE DATE DEFAULT SYSDATE NOT NULL,
    UPD_DATE DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_COUPONS PRIMARY KEY (COUPON_NO),
    CONSTRAINT UK_COUPONS_CODE UNIQUE (COUPON_CODE),
    CONSTRAINT FK_COUPONS_ISSUED_BY_USER FOREIGN KEY (ISSUED_BY_USER_NO) REFERENCES USERS(USER_NO),
    CONSTRAINT CK_COUPONS_DISCOUNT_TYPE CHECK (DISCOUNT_TYPE IN ('AMOUNT', 'PERCENT')),
    CONSTRAINT CK_COUPONS_DISCOUNT_VALUE CHECK (DISCOUNT_VALUE > 0),
    CONSTRAINT CK_COUPONS_MAX_DISCOUNT_AMOUNT CHECK (MAX_DISCOUNT_AMOUNT IS NULL OR MAX_DISCOUNT_AMOUNT >= 0),
    CONSTRAINT CK_COUPONS_MIN_ORDER_AMOUNT CHECK (MIN_ORDER_AMOUNT >= 0),
    CONSTRAINT CK_COUPONS_DATE CHECK (END_DATE >= START_DATE),
    CONSTRAINT CK_COUPONS_STATUS CHECK (STATUS IN ('ACTIVE', 'INACTIVE', 'EXPIRED'))
);

CREATE SEQUENCE SEQ_COUPONS START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE TABLE LODGINGS (
    LODGING_NO NUMBER(10) NOT NULL,
    HOST_NO NUMBER(10) NOT NULL,
    LODGING_NAME VARCHAR2(200) NOT NULL,
    LODGING_TYPE VARCHAR2(50) NOT NULL,
    REGION VARCHAR2(100) NOT NULL,
    ADDRESS VARCHAR2(300) NOT NULL,
    DETAIL_ADDRESS VARCHAR2(300),
    ZIP_CODE VARCHAR2(20),
    LATITUDE NUMBER(10,7),
    LONGITUDE NUMBER(10,7),
    DESCRIPTION VARCHAR2(2000),
    CHECK_IN_TIME VARCHAR2(20),
    CHECK_OUT_TIME VARCHAR2(20),
    STATUS VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
    DELETED_AT DATE,
    REG_DATE DATE DEFAULT SYSDATE NOT NULL,
    UPD_DATE DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_LODGINGS PRIMARY KEY (LODGING_NO),
    CONSTRAINT FK_LODGINGS_HOST FOREIGN KEY (HOST_NO) REFERENCES HOST_PROFILES(HOST_NO),
    CONSTRAINT CK_LODGINGS_STATUS CHECK (STATUS IN ('ACTIVE', 'INACTIVE', 'SUSPENDED')),
    CONSTRAINT CK_LODGINGS_LATITUDE CHECK (LATITUDE IS NULL OR (LATITUDE BETWEEN -90 AND 90)),
    CONSTRAINT CK_LODGINGS_LONGITUDE CHECK (LONGITUDE IS NULL OR (LONGITUDE BETWEEN -180 AND 180))
);

CREATE SEQUENCE SEQ_LODGINGS START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE INDEX IDX_LODGINGS_SEARCH ON LODGINGS (HOST_NO, STATUS, REGION);

CREATE TABLE ROOMS (
    ROOM_NO NUMBER(10) NOT NULL,
    LODGING_NO NUMBER(10) NOT NULL,
    ROOM_NAME VARCHAR2(200) NOT NULL,
    ROOM_TYPE VARCHAR2(50) NOT NULL,
    ROOM_DESCRIPTION VARCHAR2(2000),
    MAX_GUEST_COUNT NUMBER(5) NOT NULL,
    PRICE_PER_NIGHT NUMBER(10) NOT NULL,
    ROOM_COUNT NUMBER(5) DEFAULT 1 NOT NULL,
    STATUS VARCHAR2(20) DEFAULT 'AVAILABLE' NOT NULL,
    DELETED_AT DATE,
    REG_DATE DATE DEFAULT SYSDATE NOT NULL,
    UPD_DATE DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_ROOMS PRIMARY KEY (ROOM_NO),
    CONSTRAINT FK_ROOMS_LODGING FOREIGN KEY (LODGING_NO) REFERENCES LODGINGS(LODGING_NO),
    CONSTRAINT CK_ROOMS_MAX_GUEST_COUNT CHECK (MAX_GUEST_COUNT > 0),
    CONSTRAINT CK_ROOMS_PRICE_PER_NIGHT CHECK (PRICE_PER_NIGHT >= 0),
    CONSTRAINT CK_ROOMS_ROOM_COUNT CHECK (ROOM_COUNT > 0),
    CONSTRAINT CK_ROOMS_STATUS CHECK (STATUS IN ('AVAILABLE', 'UNAVAILABLE', 'SUSPENDED'))
);

CREATE SEQUENCE SEQ_ROOMS START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE INDEX IDX_ROOMS_LODGING_STATUS ON ROOMS (LODGING_NO, STATUS);

CREATE TABLE USER_COUPONS (
    USER_COUPON_NO NUMBER(10) NOT NULL,
    USER_NO NUMBER(10) NOT NULL,
    COUPON_NO NUMBER(10) NOT NULL,
    ISSUED_AT DATE DEFAULT SYSDATE NOT NULL,
    USED_AT DATE,
    EXPIRED_AT DATE,
    STATUS VARCHAR2(20) DEFAULT 'ISSUED' NOT NULL,
    REG_DATE DATE DEFAULT SYSDATE NOT NULL,
    UPD_DATE DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_USER_COUPONS PRIMARY KEY (USER_COUPON_NO),
    CONSTRAINT FK_USER_COUPONS_USER FOREIGN KEY (USER_NO) REFERENCES USERS(USER_NO),
    CONSTRAINT FK_USER_COUPONS_COUPON FOREIGN KEY (COUPON_NO) REFERENCES COUPONS(COUPON_NO),
    CONSTRAINT CK_USER_COUPONS_STATUS CHECK (STATUS IN ('ISSUED', 'USED', 'EXPIRED', 'CANCELED'))
);

CREATE SEQUENCE SEQ_USER_COUPONS START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE INDEX IDX_USER_COUPONS_USER_STATUS ON USER_COUPONS (USER_NO, STATUS, EXPIRED_AT);

CREATE TABLE EVENT_COUPONS (
    EVENT_COUPON_NO NUMBER(10) NOT NULL,
    EVENT_NO NUMBER(10) NOT NULL,
    COUPON_NO NUMBER(10) NOT NULL,
    REG_DATE DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_EVENT_COUPONS PRIMARY KEY (EVENT_COUPON_NO),
    CONSTRAINT FK_EVENT_COUPONS_EVENT FOREIGN KEY (EVENT_NO) REFERENCES EVENTS(EVENT_NO),
    CONSTRAINT FK_EVENT_COUPONS_COUPON FOREIGN KEY (COUPON_NO) REFERENCES COUPONS(COUPON_NO),
    CONSTRAINT UK_EVENT_COUPONS_EVENT_COUPON UNIQUE (EVENT_NO, COUPON_NO)
);

CREATE SEQUENCE SEQ_EVENT_COUPONS START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE TABLE BOOKINGS (
    BOOKING_NO NUMBER(10) NOT NULL,
    USER_NO NUMBER(10) NOT NULL,
    ROOM_NO NUMBER(10) NOT NULL,
    USER_COUPON_NO NUMBER(10),
    CHECK_IN_DATE DATE NOT NULL,
    CHECK_OUT_DATE DATE NOT NULL,
    GUEST_COUNT NUMBER(5) NOT NULL,
    PRICE_PER_NIGHT NUMBER(10) NOT NULL,
    DISCOUNT_AMOUNT NUMBER(10) DEFAULT 0 NOT NULL,
    TOTAL_PRICE NUMBER(10) NOT NULL,
    STATUS VARCHAR2(20) DEFAULT 'PENDING' NOT NULL,
    REQUEST_MESSAGE VARCHAR2(500),
    CANCELED_BY_USER_NO NUMBER(10),
    CANCELED_AT DATE,
    REG_DATE DATE DEFAULT SYSDATE NOT NULL,
    UPD_DATE DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_BOOKINGS PRIMARY KEY (BOOKING_NO),
    CONSTRAINT FK_BOOKINGS_USER FOREIGN KEY (USER_NO) REFERENCES USERS(USER_NO),
    CONSTRAINT FK_BOOKINGS_ROOM FOREIGN KEY (ROOM_NO) REFERENCES ROOMS(ROOM_NO),
    CONSTRAINT FK_BOOKINGS_USER_COUPON FOREIGN KEY (USER_COUPON_NO) REFERENCES USER_COUPONS(USER_COUPON_NO),
    CONSTRAINT FK_BOOKINGS_CANCELED_BY FOREIGN KEY (CANCELED_BY_USER_NO) REFERENCES USERS(USER_NO),
    CONSTRAINT CK_BOOKINGS_GUEST_COUNT CHECK (GUEST_COUNT > 0),
    CONSTRAINT CK_BOOKINGS_PRICE_PER_NIGHT CHECK (PRICE_PER_NIGHT >= 0),
    CONSTRAINT CK_BOOKINGS_DISCOUNT_AMOUNT CHECK (DISCOUNT_AMOUNT >= 0),
    CONSTRAINT CK_BOOKINGS_TOTAL_PRICE CHECK (TOTAL_PRICE >= 0),
    CONSTRAINT CK_BOOKINGS_DATE CHECK (CHECK_OUT_DATE > CHECK_IN_DATE),
    CONSTRAINT CK_BOOKINGS_STATUS CHECK (STATUS IN ('PENDING', 'CONFIRMED', 'CANCELED', 'COMPLETED', 'NO_SHOW'))
);

CREATE SEQUENCE SEQ_BOOKINGS START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE INDEX IDX_BOOKINGS_USER_STATUS ON BOOKINGS (USER_NO, STATUS, CHECK_IN_DATE);
CREATE INDEX IDX_BOOKINGS_ROOM_DATES ON BOOKINGS (ROOM_NO, CHECK_IN_DATE, CHECK_OUT_DATE, STATUS);

CREATE TABLE PAYMENTS (
    PAYMENT_NO NUMBER(10) NOT NULL,
    BOOKING_NO NUMBER(10) NOT NULL,
    PAYMENT_ID VARCHAR2(100) NOT NULL,
    STORE_ID VARCHAR2(100),
    CHANNEL_KEY VARCHAR2(200),
    ORDER_NAME VARCHAR2(200) NOT NULL,
    PAYMENT_AMOUNT NUMBER(10) NOT NULL,
    CURRENCY VARCHAR2(10) DEFAULT 'KRW' NOT NULL,
    PAY_METHOD VARCHAR2(30) NOT NULL,
    PG_PROVIDER VARCHAR2(30),
    PAYMENT_STATUS VARCHAR2(20) DEFAULT 'READY' NOT NULL,
    APPROVED_AT DATE,
    CANCELED_AT DATE,
    REFUND_AMOUNT NUMBER(10) DEFAULT 0 NOT NULL,
    FAIL_REASON VARCHAR2(500),
    RAW_RESPONSE CLOB,
    REG_DATE DATE DEFAULT SYSDATE NOT NULL,
    UPD_DATE DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_PAYMENTS PRIMARY KEY (PAYMENT_NO),
    CONSTRAINT FK_PAYMENTS_BOOKING FOREIGN KEY (BOOKING_NO) REFERENCES BOOKINGS(BOOKING_NO),
    CONSTRAINT UK_PAYMENTS_BOOKING UNIQUE (BOOKING_NO),
    CONSTRAINT UK_PAYMENTS_PAYMENT_ID UNIQUE (PAYMENT_ID),
    CONSTRAINT CK_PAYMENTS_AMOUNT CHECK (PAYMENT_AMOUNT >= 0),
    CONSTRAINT CK_PAYMENTS_REFUND_AMOUNT CHECK (REFUND_AMOUNT >= 0 AND REFUND_AMOUNT <= PAYMENT_AMOUNT),
    CONSTRAINT CK_PAYMENTS_PAY_METHOD CHECK (PAY_METHOD IN ('CARD', 'BANK_TRANSFER', 'VIRTUAL_ACCOUNT', 'MOBILE', 'EASY_PAY')),
    CONSTRAINT CK_PAYMENTS_PAYMENT_STATUS CHECK (PAYMENT_STATUS IN ('READY', 'PAID', 'FAILED', 'CANCELED', 'PARTIAL_CANCELED', 'REFUNDED'))
);

CREATE SEQUENCE SEQ_PAYMENTS START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE INDEX IDX_PAYMENTS_STATUS ON PAYMENTS (BOOKING_NO, PAYMENT_STATUS);

CREATE TABLE LODGING_IMAGES (
    IMAGE_NO NUMBER(10) NOT NULL,
    LODGING_NO NUMBER(10) NOT NULL,
    IMAGE_URL VARCHAR2(300) NOT NULL,
    SORT_ORDER NUMBER(3) DEFAULT 1 NOT NULL,
    REG_DATE DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_LODGING_IMAGES PRIMARY KEY (IMAGE_NO),
    CONSTRAINT FK_LODGING_IMAGES_LODGING FOREIGN KEY (LODGING_NO) REFERENCES LODGINGS(LODGING_NO),
    CONSTRAINT CK_LODGING_IMAGES_SORT_ORDER CHECK (SORT_ORDER > 0)
);

CREATE SEQUENCE SEQ_LODGING_IMAGES START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE TABLE REVIEWS (
    REVIEW_NO NUMBER(10) NOT NULL,
    BOOKING_NO NUMBER(10) NOT NULL,
    USER_NO NUMBER(10) NOT NULL,
    LODGING_NO NUMBER(10) NOT NULL,
    RATING NUMBER(2) NOT NULL,
    CONTENT VARCHAR2(1000) NOT NULL,
    REVIEW_STATUS VARCHAR2(20) DEFAULT 'VISIBLE' NOT NULL,
    REG_DATE DATE DEFAULT SYSDATE NOT NULL,
    UPD_DATE DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_REVIEWS PRIMARY KEY (REVIEW_NO),
    CONSTRAINT FK_REVIEWS_BOOKING FOREIGN KEY (BOOKING_NO) REFERENCES BOOKINGS(BOOKING_NO),
    CONSTRAINT FK_REVIEWS_USER FOREIGN KEY (USER_NO) REFERENCES USERS(USER_NO),
    CONSTRAINT FK_REVIEWS_LODGING FOREIGN KEY (LODGING_NO) REFERENCES LODGINGS(LODGING_NO),
    CONSTRAINT UK_REVIEWS_BOOKING UNIQUE (BOOKING_NO),
    CONSTRAINT CK_REVIEWS_RATING CHECK (RATING BETWEEN 1 AND 5),
    CONSTRAINT CK_REVIEWS_STATUS CHECK (REVIEW_STATUS IN ('VISIBLE', 'HIDDEN', 'REPORTED'))
);

CREATE SEQUENCE SEQ_REVIEWS START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE INDEX IDX_REVIEWS_LODGING_DATE ON REVIEWS (LODGING_NO, REG_DATE);

CREATE TABLE REVIEW_IMAGES (
    REVIEW_IMAGE_NO NUMBER(10) NOT NULL,
    REVIEW_NO NUMBER(10) NOT NULL,
    IMAGE_URL VARCHAR2(300) NOT NULL,
    SORT_ORDER NUMBER(3) DEFAULT 1 NOT NULL,
    REG_DATE DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_REVIEW_IMAGES PRIMARY KEY (REVIEW_IMAGE_NO),
    CONSTRAINT FK_REVIEW_IMAGES_REVIEW FOREIGN KEY (REVIEW_NO) REFERENCES REVIEWS(REVIEW_NO),
    CONSTRAINT CK_REVIEW_IMAGES_SORT_ORDER CHECK (SORT_ORDER > 0)
);

CREATE SEQUENCE SEQ_REVIEW_IMAGES START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE TABLE WISHLISTS (
    WISHLIST_NO NUMBER(10) NOT NULL,
    USER_NO NUMBER(10) NOT NULL,
    LODGING_NO NUMBER(10) NOT NULL,
    REG_DATE DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_WISHLISTS PRIMARY KEY (WISHLIST_NO),
    CONSTRAINT FK_WISHLISTS_USER FOREIGN KEY (USER_NO) REFERENCES USERS(USER_NO),
    CONSTRAINT FK_WISHLISTS_LODGING FOREIGN KEY (LODGING_NO) REFERENCES LODGINGS(LODGING_NO),
    CONSTRAINT UK_WISHLISTS_USER_LODGING UNIQUE (USER_NO, LODGING_NO)
);

CREATE SEQUENCE SEQ_WISHLISTS START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE TABLE MILEAGE_HISTORY (
    MILEAGE_HISTORY_NO NUMBER(10) NOT NULL,
    USER_NO NUMBER(10) NOT NULL,
    BOOKING_NO NUMBER(10),
    PAYMENT_NO NUMBER(10),
    CHANGE_TYPE VARCHAR2(20) NOT NULL,
    CHANGE_AMOUNT NUMBER(12) NOT NULL,
    BALANCE_AFTER NUMBER(12) NOT NULL,
    REASON VARCHAR2(200) NOT NULL,
    STATUS VARCHAR2(20) DEFAULT 'NORMAL' NOT NULL,
    EXPIRED_AT DATE,
    REG_DATE DATE DEFAULT SYSDATE NOT NULL,
    UPD_DATE DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_MILEAGE_HISTORY PRIMARY KEY (MILEAGE_HISTORY_NO),
    CONSTRAINT FK_MILEAGE_HISTORY_USER FOREIGN KEY (USER_NO) REFERENCES USERS(USER_NO),
    CONSTRAINT FK_MILEAGE_HISTORY_BOOKING FOREIGN KEY (BOOKING_NO) REFERENCES BOOKINGS(BOOKING_NO),
    CONSTRAINT FK_MILEAGE_HISTORY_PAYMENT FOREIGN KEY (PAYMENT_NO) REFERENCES PAYMENTS(PAYMENT_NO),
    CONSTRAINT CK_MILEAGE_HISTORY_CHANGE_TYPE CHECK (CHANGE_TYPE IN ('EARN', 'USE', 'CANCEL_USE', 'EXPIRE', 'ADJUST')),
    CONSTRAINT CK_MILEAGE_HISTORY_CHANGE_AMOUNT CHECK (CHANGE_AMOUNT <> 0),
    CONSTRAINT CK_MILEAGE_HISTORY_BALANCE_AFTER CHECK (BALANCE_AFTER >= 0),
    CONSTRAINT CK_MILEAGE_HISTORY_STATUS CHECK (STATUS IN ('NORMAL', 'CANCELED'))
);

CREATE SEQUENCE SEQ_MILEAGE_HISTORY START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE TABLE USER_REFRESH_TOKENS (
    REFRESH_TOKEN_NO NUMBER(10) NOT NULL,
    USER_NO NUMBER(10) NOT NULL,
    TOKEN_VALUE VARCHAR2(500) NOT NULL,
    EXPIRES_AT DATE NOT NULL,
    REVOKED_YN CHAR(1) DEFAULT '0' NOT NULL,
    REVOKED_AT DATE,
    REG_DATE DATE DEFAULT SYSDATE NOT NULL,
    UPD_DATE DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_USER_REFRESH_TOKENS PRIMARY KEY (REFRESH_TOKEN_NO),
    CONSTRAINT FK_USER_REFRESH_TOKENS_USER FOREIGN KEY (USER_NO) REFERENCES USERS(USER_NO),
    CONSTRAINT UK_USER_REFRESH_TOKENS_TOKEN_VALUE UNIQUE (TOKEN_VALUE),
    CONSTRAINT CK_USER_REFRESH_TOKENS_REVOKED_YN CHECK (REVOKED_YN IN ('0', '1'))
);

CREATE SEQUENCE SEQ_USER_REFRESH_TOKENS START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE TABLE INQUIRY_ROOMS (
    INQUIRY_ROOM_NO NUMBER(10) NOT NULL,
    USER_NO NUMBER(10) NOT NULL,
    HOST_NO NUMBER(10),
    LODGING_NO NUMBER(10),
    BOOKING_NO NUMBER(10),
    INQUIRY_TYPE VARCHAR2(30) NOT NULL,
    TITLE VARCHAR2(200) NOT NULL,
    ROOM_STATUS VARCHAR2(20) DEFAULT 'OPEN' NOT NULL,
    LAST_MESSAGE_AT DATE DEFAULT SYSDATE NOT NULL,
    CLOSED_AT DATE,
    REG_DATE DATE DEFAULT SYSDATE NOT NULL,
    UPD_DATE DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_INQUIRY_ROOMS PRIMARY KEY (INQUIRY_ROOM_NO),
    CONSTRAINT FK_INQUIRY_ROOMS_USER FOREIGN KEY (USER_NO) REFERENCES USERS(USER_NO),
    CONSTRAINT FK_INQUIRY_ROOMS_HOST FOREIGN KEY (HOST_NO) REFERENCES HOST_PROFILES(HOST_NO),
    CONSTRAINT FK_INQUIRY_ROOMS_LODGING FOREIGN KEY (LODGING_NO) REFERENCES LODGINGS(LODGING_NO),
    CONSTRAINT FK_INQUIRY_ROOMS_BOOKING FOREIGN KEY (BOOKING_NO) REFERENCES BOOKINGS(BOOKING_NO),
    CONSTRAINT CK_INQUIRY_ROOMS_TYPE CHECK (INQUIRY_TYPE IN ('LODGING', 'BOOKING', 'PAYMENT', 'SYSTEM')),
    CONSTRAINT CK_INQUIRY_ROOMS_STATUS CHECK (ROOM_STATUS IN ('OPEN', 'ANSWERED', 'CLOSED', 'BLOCKED'))
);

CREATE SEQUENCE SEQ_INQUIRY_ROOMS START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE INDEX IDX_INQUIRY_ROOMS_USER_STATUS ON INQUIRY_ROOMS (USER_NO, ROOM_STATUS, INQUIRY_TYPE);

CREATE TABLE INQUIRY_MESSAGES (
    INQUIRY_MESSAGE_NO NUMBER(10) NOT NULL,
    INQUIRY_ROOM_NO NUMBER(10) NOT NULL,
    SENDER_USER_NO NUMBER(10) NOT NULL,
    SENDER_ROLE_CODE VARCHAR2(30) NOT NULL,
    MESSAGE_TYPE VARCHAR2(20) DEFAULT 'TEXT' NOT NULL,
    CONTENT CLOB NOT NULL,
    IS_READ CHAR(1) DEFAULT '0' NOT NULL,
    READ_AT DATE,
    REG_DATE DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_INQUIRY_MESSAGES PRIMARY KEY (INQUIRY_MESSAGE_NO),
    CONSTRAINT FK_INQUIRY_MESSAGES_ROOM FOREIGN KEY (INQUIRY_ROOM_NO) REFERENCES INQUIRY_ROOMS(INQUIRY_ROOM_NO),
    CONSTRAINT FK_INQUIRY_MESSAGES_SENDER FOREIGN KEY (SENDER_USER_NO) REFERENCES USERS(USER_NO),
    CONSTRAINT CK_INQUIRY_MESSAGES_SENDER_ROLE CHECK (SENDER_ROLE_CODE IN ('ROLE_USER', 'ROLE_HOST', 'ROLE_ADMIN')),
    CONSTRAINT CK_INQUIRY_MESSAGES_TYPE CHECK (MESSAGE_TYPE IN ('TEXT', 'IMAGE', 'SYSTEM')),
    CONSTRAINT CK_INQUIRY_MESSAGES_IS_READ CHECK (IS_READ IN ('0', '1'))
);

CREATE SEQUENCE SEQ_INQUIRY_MESSAGES START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE INDEX IDX_INQUIRY_MESSAGES_ROOM_DATE ON INQUIRY_MESSAGES (INQUIRY_ROOM_NO, REG_DATE);

CREATE TABLE AUDIT_LOGS (
    AUDIT_LOG_NO NUMBER(10) NOT NULL,
    ACTOR_USER_NO NUMBER(10) NOT NULL,
    TARGET_TABLE VARCHAR2(50) NOT NULL,
    TARGET_NO NUMBER(10),
    ACTION_CODE VARCHAR2(50) NOT NULL,
    DETAIL_JSON CLOB,
    REG_DATE DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_AUDIT_LOGS PRIMARY KEY (AUDIT_LOG_NO),
    CONSTRAINT FK_AUDIT_LOGS_ACTOR FOREIGN KEY (ACTOR_USER_NO) REFERENCES USERS(USER_NO)
);

CREATE SEQUENCE SEQ_AUDIT_LOGS START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE INDEX IDX_AUDIT_LOGS_TARGET ON AUDIT_LOGS (TARGET_TABLE, TARGET_NO, REG_DATE);
